M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Sat 15 Jul 2023 17:42:57 -03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-15T17:42:57-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.825Y-4.675
X4.9625Y-3.1625
X7.025Y-3.15
X7.175Y-4.675
T0
M30
